[project]
name = "screencap"
version = "0.1.0"
description = ""
authors = [{ name = "goldentoaste", email = "rayg2375@gmail.com" }]
license = { text = "GPL" }
readme = "README.md"
dependencies = [
    "pyside6 (>=6.10)",
    "pywin32 (>=311,<312) ; sys_platform == \"win32\"",
    "evdev (>=1.9.3,<2.0.0) ; sys_platform == \"linux\"",
]


[dependency-groups]
dev = [
    "nuitka>=4.1.2",
]

[tool.uv]
package = true